import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'

const heroImage = 'https://shaholanisha.xyz/wp-content/uploads/2026/01/magpie.png'

const services = [
  ['01', 'Fund Transfer', 'Move money across own accounts, Basic Bank accounts and other banks.'],
  ['02', 'MFS Transfer', 'Support mobile financial service transfers from the banking experience.'],
  ['03', 'Utility Bills', 'Bring recurring bill payments into the same everyday banking workflow.'],
  ['04', 'Mobile Recharge', 'Make quick recharge actions easy to find and complete.'],
  ['05', 'Cards & Accounts', 'Manage accounts, cards and beneficiaries without leaving the app.'],
  ['06', 'Transaction History', 'Give users a clear record of previous financial activity.'],
]
const decisions = [
  ['Prioritise everyday actions', 'The home experience surfaces high-frequency services instead of making users search through a long banking menu.'],
  ['Group by user intent', 'Transfer, recharge, bills, accounts and history are organised around what customers want to do.'],
  ['Reduce transaction anxiety', 'Review, verification and confirmation states make money movement deliberate and easy to understand.'],
  ['Keep patterns consistent', 'Reusable UI patterns make different financial services feel like one product.'],
]
function SectionLabel({ number, children }) { return <div className="flex items-center gap-3 mb-7"><span className="font-mono text-xs text-zinc-400">{number}</span><span className="h-px w-8 bg-zinc-300"/><span className="font-mono text-xs uppercase tracking-[.2em] text-zinc-500">{children}</span></div> }
export default function BasicBankMagpieCaseStudyPage() {
 return <div className="min-h-screen bg-[#f8f9f8] text-zinc-900 antialiased">
  <header className="fixed top-0 left-0 right-0 z-50 bg-[#f8f9f8]/90 backdrop-blur-xl border-b border-zinc-200/70"><div className="max-w-7xl mx-auto px-6 lg:px-10 h-16 flex items-center justify-between"><Link to="/" className="font-display font-bold text-lg tracking-tight">Shahola</Link><Link to="/" className="text-sm text-zinc-600 hover:text-zinc-950">← Back to work</Link></div></header>
  <main className="pt-16">
   <section className="border-b border-zinc-200 bg-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-14 lg:py-20">
    <motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.65}}><div className="flex flex-wrap items-center gap-2 mb-7">{['Mobile Banking','Financial Services','Figma'].map(tag=><span key={tag} className="px-3 py-2 rounded-lg border border-zinc-200 bg-zinc-50 text-xs font-medium text-zinc-600">{tag}</span>)}</div>
     <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8"><div className="max-w-4xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-zinc-400 mb-5">Basic Bank · Sep–Oct 2022</p><h1 className="font-display text-5xl sm:text-6xl lg:text-8xl font-bold tracking-[-.045em] leading-[.92]">Basic Bank —<br/><span className="text-zinc-300">Magpie Financial Services</span></h1><p className="mt-7 max-w-3xl text-lg lg:text-xl leading-8 text-zinc-600">A mobile banking solution for Basic Bank customers to manage finances, transfer funds, pay bills and access everyday financial services from one app.</p></div>
      <div className="shrink-0 grid grid-cols-2 gap-x-10 gap-y-5 text-sm min-w-[250px]">{[['Client','Basic Bank'],['Product','Magpie'],['Role','UX / UI Design'],['Platform','Mobile App']].map(([a,b])=><div key={a}><span className="block text-[10px] font-mono uppercase tracking-widest text-zinc-400">{a}</span><strong>{b}</strong></div>)}</div>
     </div></motion.div>
    <motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.15}} className="mt-14 rounded-[28px] overflow-hidden border border-zinc-200 bg-zinc-100"><img src={heroImage} alt="Basic Bank Magpie mobile banking app" className="w-full block" /></motion.div>
   </div></section>
   <nav className="sticky top-16 z-40 bg-white/90 backdrop-blur border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-4 flex gap-8 min-w-max overflow-x-auto">{['Overview','Challenge','Approach','Services','Transfer','Outcome'].map((x,i)=><a key={x} href={`#s${i+1}`} className="font-mono text-[10px] uppercase tracking-[.14em] text-zinc-400 hover:text-zinc-900">0{i+1} {x}</a>)}</div></nav>
   <section id="s1" className="border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32 grid lg:grid-cols-12 gap-14"><div className="lg:col-span-4"><SectionLabel number="01">Overview</SectionLabel><h2 className="font-display text-5xl lg:text-6xl font-bold tracking-tight leading-[1.02]">Banking,<br/><span className="text-zinc-300">in one place.</span></h2></div><div className="lg:col-span-7 lg:col-start-6"><p className="text-2xl leading-[1.55] font-light">Magpie brought the core services of Basic Bank into a single mobile experience.</p><p className="mt-8 text-base leading-7 text-zinc-600">The product was designed around everyday jobs: checking accounts, transferring money, managing beneficiaries, paying bills, recharging mobile numbers and reviewing transactions.</p></div></div></section>
   <section id="s2" className="border-b border-zinc-200 bg-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32 grid lg:grid-cols-12 gap-14"><div className="lg:col-span-4"><SectionLabel number="02">Challenge</SectionLabel><h2 className="font-display text-5xl lg:text-6xl font-bold tracking-tight">Make a complex bank feel <span className="text-zinc-300">simple.</span></h2></div><div className="lg:col-span-7 lg:col-start-6"><p className="text-2xl leading-[1.55] font-light">A mobile banking app can quickly become a collection of services rather than a coherent product.</p><p className="mt-8 text-base leading-7 text-zinc-600">Magpie needed to expose a broad set of financial capabilities while keeping the experience approachable. The design challenge was balancing service depth with discoverability, especially around actions involving money.</p><div className="mt-10 border-l-2 border-zinc-900 pl-6"><p className="text-lg font-medium leading-7">How might we help customers complete everyday financial tasks without making them navigate the bank's internal complexity?</p></div></div></div></section>
   <section id="s3" className="border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><SectionLabel number="03">Approach</SectionLabel><div className="grid lg:grid-cols-2 gap-16"><h2 className="font-display text-5xl lg:text-7xl font-bold tracking-tight leading-[.98]">Design around<br/><span className="text-zinc-300">what people do.</span></h2><div className="grid sm:grid-cols-2 gap-8">{decisions.map(([title,text],i)=><div key={title} className="border-t border-zinc-200 pt-5"><span className="font-mono text-xs text-zinc-400">0{i+1}</span><h3 className="font-semibold mt-4">{title}</h3><p className="text-sm leading-6 text-zinc-600 mt-3">{text}</p></div>)}</div></div></div></section>
   <section id="s4" className="border-b border-zinc-200 bg-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><SectionLabel number="04">Core services</SectionLabel><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-14"><h2 className="font-display text-5xl lg:text-7xl font-bold tracking-tight leading-[.98]">A broad banking<br/><span className="text-zinc-300">toolkit.</span></h2><p className="max-w-md text-zinc-600 leading-7">The home experience brings the most important financial services into reach without overwhelming the customer.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 border-l border-t border-zinc-200">{services.map(([n,title,text])=><div key={title} className="border-r border-b border-zinc-200 p-7 lg:p-9 min-h-[220px]"><span className="font-mono text-xs text-zinc-400">{n}</span><h3 className="font-display text-2xl font-semibold mt-10">{title}</h3><p className="text-sm text-zinc-600 leading-6 mt-3">{text}</p></div>)}</div></div></section>
   <section id="s5" className="border-b border-zinc-200 bg-[#eef3e8]"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><SectionLabel number="05">Fund transfer</SectionLabel><div className="grid lg:grid-cols-12 gap-14 items-center"><div className="lg:col-span-5"><h2 className="font-display text-5xl lg:text-6xl font-bold tracking-tight leading-[1.02]">When money moves,<br/><span className="text-zinc-400">clarity matters.</span></h2><p className="mt-7 text-zinc-600 leading-7">Fund transfer is treated as a deliberate journey: select the transfer type, choose the account and destination, enter the amount, review the details and complete authentication.</p><div className="mt-9 space-y-3">{['Transfer type','From account','To beneficiary','Amount','Review & confirm','Authentication'].map((x,i)=><div key={x} className="flex items-center gap-4"><span className="w-7 h-7 rounded-full bg-zinc-900 text-white flex items-center justify-center text-[10px] font-mono">{i+1}</span><span className="text-sm font-medium">{x}</span></div>)}</div></div><div className="lg:col-span-7 grid grid-cols-2 gap-5"><div className="rounded-3xl bg-white border border-zinc-200 p-5"><div className="font-mono text-[10px] uppercase tracking-widest text-zinc-400">Select account</div><div className="mt-5 rounded-2xl border border-zinc-200 p-5"><div className="text-xs text-zinc-400">FROM</div><div className="font-semibold mt-2">Basic Bank Current Account</div><div className="text-xs text-zinc-500 mt-1">•••• 4498</div></div></div><div className="rounded-3xl bg-zinc-900 text-white p-5"><div className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Review</div><div className="mt-5 space-y-4 text-sm"><div className="flex justify-between border-b border-white/10 pb-3"><span className="text-zinc-400">Recipient</span><span>Beneficiary</span></div><div className="flex justify-between border-b border-white/10 pb-3"><span className="text-zinc-400">Amount</span><span>৳ 12,500</span></div><div className="flex justify-between"><span className="text-zinc-400">Status</span><span>Ready to confirm</span></div></div></div></div></div></div></section>
   <section id="s6" className="bg-zinc-950 text-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><SectionLabel number="06">Outcome</SectionLabel><div className="grid lg:grid-cols-2 gap-16"><div><h2 className="font-display text-5xl lg:text-7xl font-bold tracking-tight leading-[.98]">One app.<br/><span className="text-zinc-600">Everyday banking.</span></h2></div><div><p className="text-xl lg:text-2xl leading-9 text-zinc-300">Magpie translated a wide range of Basic Bank services into a cohesive mobile experience, with clear entry points for transfers, payments, accounts and transaction activity.</p><div className="mt-12 pt-8 border-t border-white/10"><p className="text-sm uppercase tracking-[.16em] font-mono text-zinc-500">What I learned</p><p className="mt-4 text-lg leading-8 text-zinc-300">For financial products, clarity is part of the interface. Every important action needs a visible purpose, a clear next step and confident feedback.</p></div></div></div><div className="mt-16 flex flex-wrap gap-3"><a href="https://www.figma.com/design/yWbqQUeITrZfcK3vmt3DoJ/Basic-Bank-Internet-Banking?node-id=55051-16545" target="_blank" rel="noreferrer" className="rounded-full bg-white text-zinc-950 px-5 py-3 text-sm font-medium hover:bg-zinc-200">View Figma project ↗</a><Link to="/" className="rounded-full border border-white/20 px-5 py-3 text-sm font-medium hover:bg-white/10">Back to portfolio</Link></div></div></section>
  </main>
 </div>
}
