import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import logo from '../assets/logo.png'

const sections = [['01','Overview'],['02','Challenge'],['03','Approach'],['04','Core journeys'],['05','Fund transfer'],['06','Design system'],['07','Outcome']]
const journeys = [
  ['Account management','View account information, balances and recent activity from one place.'],
  ['Fund transfer','Structured journeys for own-account, Basic Bank and other-bank transfers.'],
  ['Beneficiary management','Save and manage recipients so repeat transfers require less effort.'],
  ['Payments & recharge','Bring utility bills, credit-card payments and mobile recharge together.'],
  ['Transaction history','Scan previous activity through amount, date, type and status.'],
  ['Security & confirmation','Make high-risk financial actions deliberate and understandable.'],
]
const principles = [
  ['Make the next action obvious','Prioritise the action users came to complete instead of exposing system complexity at once.'],
  ['One decision at a time','Break financial tasks into focused steps so users can concentrate on what matters.'],
  ['Confirm before money moves','Create a deliberate review moment for recipient, account, amount and transaction details.'],
  ['Keep states predictable','Use consistent loading, success, failure, empty and verification patterns.'],
]
function Label({number,children}){return <div className="flex items-center gap-3 mb-7"><span className="font-mono text-xs text-zinc-400">{number}</span><span className="h-px w-8 bg-zinc-300"/><span className="font-mono text-xs uppercase tracking-[.2em] text-zinc-500">{children}</span></div>}
function Phone({variant=0}){
 const screens=[
  <><div className="text-[9px] text-zinc-400">GOOD MORNING</div><div className="text-lg font-semibold mt-1">Welcome back</div><div className="mt-6 rounded-2xl bg-zinc-100 p-4"><div className="text-[8px] text-zinc-400">AVAILABLE BALANCE</div><div className="text-2xl font-semibold mt-1">৳ 48,250.00</div></div><div className="grid grid-cols-2 gap-2 mt-3">{['Transfer','Pay bill','Recharge','History'].map(x=><div className="rounded-xl border border-zinc-200 p-3 text-[9px] font-medium" key={x}>{x}</div>)}</div></>,
  <><div className="text-[9px] text-zinc-400">FUND TRANSFER</div><div className="text-lg font-semibold mt-1">Select account</div><div className="mt-5 rounded-xl border border-zinc-200 p-3"><div className="text-[8px] text-zinc-400">FROM</div><div className="text-[10px] font-medium mt-1">Savings Account</div><div className="text-[9px] text-zinc-500 mt-1">•••• 2387 · ৳ 48,250</div></div><div className="mt-2 rounded-xl border border-zinc-200 p-3"><div className="text-[8px] text-zinc-400">TO</div><div className="text-[10px] font-medium mt-1">Select beneficiary</div></div><div className="mt-4 h-9 rounded-xl bg-zinc-900 text-white flex items-center justify-center text-[9px]">Continue</div></>,
  <><div className="text-[9px] text-zinc-400">REVIEW TRANSFER</div><div className="text-lg font-semibold mt-1">Check the details</div><div className="mt-5 space-y-3">{[['Recipient','Rahim Ahmed'],['Account','•••• 9012'],['Amount','৳ 12,500'],['Purpose','Family transfer']].map(([a,b])=><div className="flex justify-between border-b border-zinc-100 pb-2" key={a}><span className="text-[8px] text-zinc-400">{a}</span><span className="text-[9px] font-medium">{b}</span></div>)}</div><div className="mt-5 h-9 rounded-xl bg-zinc-900 text-white flex items-center justify-center text-[9px]">Confirm & transfer</div></>
 ]
 return <div className="w-[210px] sm:w-[235px] rounded-[30px] border-[7px] border-zinc-900 bg-white shadow-2xl p-4 min-h-[430px]">{screens[variant]}</div>
}
export default function BasicBankMagpieCaseStudyPage(){return <div className="min-h-screen bg-[#fafafa] text-zinc-900 antialiased">
 <header className="fixed top-0 left-0 right-0 z-50 bg-[#fafafa]/85 backdrop-blur-xl border-b border-zinc-200/70"><div className="max-w-7xl mx-auto px-6 lg:px-10 h-16 flex items-center justify-between"><Link to="/" className="flex items-center"><img src={logo} alt="Alimoon Nisha" className="h-14 w-auto"/></Link><Link to="/" className="text-sm text-zinc-600 hover:text-zinc-950">← Back to work</Link></div></header>
 <main className="pt-16">
  <section className="border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-20 lg:py-28"><div className="grid lg:grid-cols-12 gap-14 items-center"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="lg:col-span-7"><div className="flex items-center gap-3 mb-8"><span className="font-mono text-xs uppercase tracking-[.2em] text-zinc-500">Case Study</span><span className="w-1 h-1 rounded-full bg-zinc-400"/><span className="font-mono text-xs text-zinc-500">BASIC BANK</span></div><h1 className="font-display font-bold tracking-[-.045em] leading-[.95] text-[clamp(3.5rem,8vw,7.2rem)]">Magpie<br/><span className="text-zinc-300">Financial Services</span></h1><p className="mt-8 max-w-2xl text-lg lg:text-xl leading-8 text-zinc-600">Designing a structured digital banking experience that brings accounts, transfers, beneficiaries and everyday payments into one clear financial workspace.</p><div className="flex flex-wrap gap-2 mt-8">{['UX / UI Design','Internet Banking','Fintech','Figma'].map(x=><span key={x} className="px-3 py-2 rounded-full border border-zinc-200 bg-white text-xs font-medium text-zinc-600">{x}</span>)}</div></motion.div><motion.div initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{duration:.8}} className="lg:col-span-5 flex justify-center lg:justify-end"><div className="relative"><div className="absolute -inset-10 bg-zinc-200/60 blur-3xl rounded-full"/><Phone/><div className="absolute -right-16 bottom-8 hidden sm:block rotate-6"><Phone variant={1}/></div></div></motion.div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-8 border-t border-zinc-200 mt-20 pt-8">{[['Client','Basic Bank'],['Product','Magpie Financial Services'],['Role','UX / UI Design'],['Platform','Internet Banking']].map(([a,b])=><div key={a}><div className="font-mono text-[10px] uppercase tracking-[.16em] text-zinc-400">{a}</div><div className="mt-2 text-sm font-semibold">{b}</div></div>)}</div></div></section>
  <section className="border-b border-zinc-200 bg-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-5 overflow-x-auto"><div className="flex gap-8 min-w-max">{sections.map(([n,t])=><a key={n} href={`#s${n}`} className="font-mono text-[10px] uppercase tracking-[.14em] text-zinc-400 hover:text-zinc-900">{n} {t}</a>)}</div></div></section>
  <section id="s02" className="border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32 grid lg:grid-cols-12 gap-14"><div className="lg:col-span-4"><Label number="02">The challenge</Label><h2 className="font-display text-5xl lg:text-6xl font-bold tracking-tight leading-[1.02]">Banking has a lot to say.</h2></div><div className="lg:col-span-7 lg:col-start-6"><p className="text-2xl leading-[1.55] font-light">The challenge was to turn a broad set of financial services into an experience that feels understandable at the point of use.</p><p className="mt-8 text-base leading-7 text-zinc-600">Transfers, beneficiaries, payments, accounts and transaction history each have their own rules. The interface needed to expose those capabilities without making users learn the bank's internal structure before completing a task.</p><div className="mt-10 border-l-2 border-zinc-900 pl-6"><p className="text-lg font-medium leading-7">How might we make everyday banking feel simple and predictable while keeping the controls and confirmation needed for financial actions?</p></div></div></div></section>
  <section id="s03" className="border-b border-zinc-200 bg-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><Label number="03">Approach</Label><div className="grid lg:grid-cols-2 gap-16"><div><h2 className="font-display text-5xl lg:text-7xl font-bold tracking-tight leading-[.98]">Organise around<br/><span className="text-zinc-300">user intent.</span></h2></div><div className="grid sm:grid-cols-2 gap-8">{principles.map(([t,d],i)=><div key={t} className="border-t border-zinc-200 pt-5"><div className="font-mono text-xs text-zinc-400">0{i+1}</div><h3 className="font-semibold mt-4">{t}</h3><p className="text-sm leading-6 text-zinc-600 mt-3">{d}</p></div>)}</div></div></div></section>
  <section id="s04" className="border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><Label number="04">Core journeys</Label><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-14"><h2 className="font-display text-5xl lg:text-7xl font-bold tracking-tight leading-[.98]">A banking system,<br/><span className="text-zinc-300">mapped to tasks.</span></h2><p className="max-w-md text-zinc-600 leading-7">The experience is structured around the jobs users need to complete, keeping high-frequency actions discoverable while deeper services remain organised.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 border-l border-t border-zinc-200">{journeys.map(([t,d],i)=><div key={t} className="border-r border-b border-zinc-200 p-7 lg:p-9 min-h-[220px]"><span className="font-mono text-xs text-zinc-400">0{i+1}</span><h3 className="font-display text-2xl font-semibold mt-10">{t}</h3><p className="text-sm text-zinc-600 leading-6 mt-3">{d}</p></div>)}</div></div></section>
  <section id="s05" className="border-b border-zinc-200 bg-white overflow-hidden"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><Label number="05">Fund transfer</Label><div className="grid lg:grid-cols-12 gap-14 items-center"><div className="lg:col-span-5"><h2 className="font-display text-5xl lg:text-6xl font-bold tracking-tight leading-[1.02]">When money moves,<br/><span className="text-zinc-300">clarity matters.</span></h2><p className="mt-7 text-zinc-600 leading-7">Fund transfer was treated as a progressive journey: choose the transfer context, identify the destination, enter the amount, review the details and authenticate.</p><div className="mt-9 space-y-4">{['Select transfer type','Choose account & beneficiary','Enter amount','Review transaction','Authenticate','Confirmation'].map((x,i)=><div className="flex gap-4 items-center" key={x}><span className="w-7 h-7 rounded-full bg-zinc-900 text-white flex items-center justify-center text-[10px] font-mono">{i+1}</span><span className="text-sm font-medium">{x}</span></div>)}</div></div><div className="lg:col-span-7 flex gap-5 justify-center lg:justify-end items-end"><Phone variant={1}/><Phone variant={2}/></div></div></div></section>
  <section id="s06" className="border-b border-zinc-200"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><Label number="06">Visual system</Label><div className="grid lg:grid-cols-12 gap-14"><div className="lg:col-span-5"><h2 className="font-display text-5xl lg:text-6xl font-bold tracking-tight">Consistency is a<br/><span className="text-zinc-300">trust signal.</span></h2><p className="mt-7 text-zinc-600 leading-7">Reusable components keep navigation, inputs, cards, transaction rows and feedback states consistent across journeys.</p></div><div className="lg:col-span-7"><div className="rounded-3xl bg-zinc-950 text-white p-8 lg:p-12"><div className="font-mono text-[10px] uppercase tracking-[.2em] text-zinc-500">Component language</div><div className="grid grid-cols-2 gap-3 mt-8">{['Buttons','Account cards','Inputs','Beneficiary rows','Transaction items','Tabs','Alerts','Success states','Empty states','Confirmation'].map(x=><div key={x} className="rounded-xl border border-white/10 px-4 py-4 text-sm">{x}</div>)}</div><div className="flex gap-2 mt-8">{['#111111','#989898','#D1D1D1','#FFFFFF','#46B679','#FFD80C','#F98A17'].map(c=><span key={c} className="w-10 h-10 rounded-full border border-white/10" style={{background:c}}/>)}</div></div></div></div></div></section>
  <section id="s07" className="bg-zinc-950 text-white"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 lg:py-32"><Label number="07">Outcome & learning</Label><div className="grid lg:grid-cols-2 gap-16"><div><h2 className="font-display text-5xl lg:text-7xl font-bold tracking-tight leading-[.98]">From banking<br/><span className="text-zinc-600">services to a system.</span></h2></div><div><p className="text-xl lg:text-2xl leading-9 text-zinc-300">The work brought core banking journeys into a cohesive digital experience with a consistent interaction language across account management, transfers and payments.</p><div className="mt-12 pt-8 border-t border-white/10"><p className="text-sm uppercase tracking-[.16em] font-mono text-zinc-500">Key takeaway</p><p className="mt-4 text-lg leading-8">Good banking UX is less about making the system look simple and more about making every decision feel clear, deliberate and reversible until the moment money moves.</p></div></div></div><div className="mt-20 pt-8 border-t border-white/10 flex flex-wrap gap-3"><a href="https://www.figma.com/design/yWbqQUeITrZfcK3vmt3DoJ/Basic-Bank-Internet-Banking?node-id=55051-16545" target="_blank" rel="noreferrer" className="rounded-full bg-white text-zinc-950 px-5 py-3 text-sm font-medium hover:bg-zinc-200">View Figma project ↗</a><Link to="/" className="rounded-full border border-white/20 px-5 py-3 text-sm font-medium hover:bg-white/10">Back to portfolio</Link></div></div></section>
 </main>
</div>}
